# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [31]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print(A) #whole array
print(A.ndim) #shows its 2 dimensional
print(A.shape) #shows it has 3 rows, 3 columns
print(A.dtype) #datatype = int32
print(A.itemsize) #size in bytes for each element, int32/8 = 4

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
int32
4


In [5]:
Z = np.array([
                     [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                     [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
print(Z)
print(Z.shape)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(2, 3, 3)


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [6]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
print(B - C) # elementwise subtraction
print(B * C) # elementwise multiplication
print(B @ C) # matrix operation

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.exp(B)) #exponantiates by e
print(np.min(B)) #shows the min value of B
print(np.min(B, axis=1)) #shows min value for all axis=1 (all rows in first column)
print(np.min(B, axis=0)) #shows min value for all axis=0 (first row, all columns)
print(np.argmin(B)) #prints the index number of the minimum value (in this case, min value is 1 which is index spot 0)
print(np.argmin(B, axis=1)) #prints index number of min value for each row (axis 1)
print(np.sum(B)) #sums all elements in array B
print(np.mean(B, axis=0)) #prints the mean of each column (when axis=0)
print(np.median(B, axis=0)) #prints the median of each column. Same as mean in this case, because of the structure of datapoints
#given

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
print(A[1])

[ 6  7  8  9 10]


**Answer:**

Returns the row index 1 and automatically fills the column index, so output is entirety of row 2. Equivalent to A[1, :]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [32]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [38]:
for i in A.ravel():    #prints each "i" (item) from A in the shape of a 1-dimensional array
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [18]:
a = np.arange(30) #creates a 1-dim array including integers 0-29
b = a.reshape((2, 3, -1)) #reshapes "a" into a multidimensional array "b" with 2 rows, 3 columns, however the -1 indicates
#that the rest of the dimensions will be auto calculated to fit all the original datapoints, in this case 2,3,5
print(a)
print()

print(b)
print(b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
(2, 3, 5)


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [43]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [44]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [45]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [20]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [21]:
#"When doing matrix addition, validate that the matrices have the same size." - in the code or generally? Assuming in our code

#define function
def add_mult_matrices(matrix1, matrix2,operation):
    #validate inputs as Numpy Arrays
    if not (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)):
        raise ValueError("Inputs need to be Numpy Arrays")
    
    #validate shapes of matrices for addition and multiplication, raise error if wrong shape
    if operation=="add" or operation=="subtract":
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have same shape for addition or subtraction")
    elif operation=="multiply":
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Matrix 1 must have same number of columns as Matrix 2 has rows for multiplication")
    #set up add, multiply operations, raise error if wrong input
    if operation == "add":
        result = matrix1 + matrix2
    elif operation == "subtract":
        result = matrix1 - matrix2
    elif operation == "multiply":
        result = (matrix1 @ matrix2) # @ = multiplikation
    else:
        raise ValueError("Can only add, subtract or multiply")
    return result
#PERFORM TASKS, first B-2A
print(add_mult_matrices(B, 2 * A, "subtract"))


#3C-E (commented out since raises shape error)
# print(add_mult_matrices(3 * C, E, "subtract"))

#A*C (commented out since raises shape error)
#print(add_mult_matrices(A, C, "multiply"))

#C*D
print(add_mult_matrices(C, D, "multiply"))

#C*B
print(add_mult_matrices(C, B, "multiply"))

[[ 0 -4  3]
 [ 0 -2 -4]]
[[11 10]
 [10 11]]
[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [23]:
A = np.array([[1, 2],[2,4]])
B = np.array([[2,1],[1,3]])
C = np.array([[4,3],[0,2]])

In [24]:
#use the function we created before or not? not sure, going with simplicity
AB=np.dot(A, B)
AC=np.dot(A, C)

if np.array_equal(AB, AC) and not np.array_equal(B, C):
    print("Same")
else:
    print("Not same")

Same


**Chap2. Question 3**

In [6]:
A = np.array([[1,1,1],[1,2,3],[1,3,4]])
D = np.array([[2,0,0],[0,3,0],[0,0,4]])

print(A @ D)
print(D @ A)

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]
[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [12]:
A = np.array([[1,-1],[-1,1]])
B = np.array([[-1,1],[1,-1]])
#create checklist from target matrices
checklist=[
    np.array([[-2,2],[2,-2]]),
    np.array([[2,-2],[-2,2]]),
    np.array([[-2,2],[-2,2]]),
    np.array([[-2,-2],[2,2]])
]
#set match and index variables to see exactly which matrices matches
match_found=False
matching_index=None

#use enumerate to simultaneously iterate through index and item(iteration names irrelevant, if given 2 arguments = index,element)
#print where in "checklist" the match was found
for index, item in enumerate(checklist):
    product = A @ B
    if np.array_equal(product, item):
        match_found=True
        matching_index=index
        print(f"Match found in index {matching_index +1}") #use (f"string") for precise output
        break
if not match_found:
    print("No match found")

Match found in index 1


**Chap 6. Question 1**

In [15]:
#might encounter rounding errors, look into .allclose later
A = ([[5,6],[4,5]])
B = ([[6,4],[3,3]])

#only works with square matrices
print(np.linalg.inv(A))
print(np.linalg.inv(B))

[[ 5. -6.]
 [-4.  5.]]
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [39]:
#problems, answer is defined as 1/2(matrix), need workaround
A = np.array([[2,2],
              [1,2]])

checklist2=[
    np.array([[2,-2],[-1,2]]),
    np.array([[-2,2],[1,-2]]),
    np.array([[2,2],[-1,-2]]),
    np.array([[-2,-2],[1,2]])
]
match_found2=False
matching_index2=None
inverse_A = np.linalg.inv(A)  #define inverse of A

for index, item in enumerate(checklist2):
    item_fix=item/2 #divide items in checklist2 by 2 for accurate answer
    
    if np.array_equal(item_fix, inverse_A):
        match_found2=True
        matching_index2=index

if match_found2==True:
    print(f"Match found in index {matching_index2}")
else:
    print("No match found")

Match found in index 0


**Chap10. Question 1 a)**

In [9]:
#create arrays from given equations
A = np.array([[3,-7,-2],
              [-3,5,1],
              [6,-4,0]
             ])
B = np.array([[-7],
             [5],
             [2]
             ])
print(np.linalg.solve(A, B)) #use np.linalg.solve to compute matrices



[[ 3.]
 [ 4.]
 [-6.]]


In [25]:
#gaussian elimination calculation, code works but struggling to understand fully

#define the coefficient matrix A and the right side vector B
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
B = np.array([[-7], [5], [2]])

#determine the number of equations/variables
n = len(B)

#create the augmented matrix by combining A and B as type=float to avoid potential problems
augmented_matrix = np.concatenate((A, B), axis=1).astype(float)

#perform Gaussian elimination with partial pivoting
for pivot_row in range(n):
    # find the row with the maximum value in the current column
    max_row = pivot_row + np.argmax(np.abs(augmented_matrix[pivot_row:, pivot_row]))
    
    #swap the pivot row and the row with the maximum value
    augmented_matrix[[pivot_row, max_row]] = augmented_matrix[[max_row, pivot_row]]
    
    #eliminate elements below the pivot
    for current_row in range(pivot_row + 1, n):
        scaling = augmented_matrix[current_row, pivot_row] / augmented_matrix[pivot_row, pivot_row]
        augmented_matrix[current_row] -= scaling * augmented_matrix[pivot_row]

#perform back substitution to find the solution
solution = np.zeros(n)
for i in range(n - 1, -1, -1):
    solution[i] = (augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i + 1:n], solution[i + 1:n])) / augmented_matrix[i, i]

print(solution)


[ 3.  4. -6.]


**Chap10. Question 1 b)**

In [54]:
A = np.array([[1,-2,3],
             [-1,3,-1],
             [2,-5,5]
             ])
B = np.array([[1],
             [-1],
             [1]
             ])

print(np.linalg.solve(A, B))

[[ 8.]
 [ 2.]
 [-1.]]


**Chap 12. Question 1**

In [40]:
#rounding errors again, needs fix
A = ([[3,-7,-2],
     [-3,5,1],
     [6,-4,0]
     ])
print(np.linalg.inv(A))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [4]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [5]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [6]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


Use .base to check if arrays are views, copies or standalones (none = standalone). If element is changed in v2, same element will not be changed in v1 since v2 is created as a sliced copy of v1, they do share data though